### ISSUE TITLE
端口问题

### ISSUE THREAD

**Issue by Dar1in9s** [D0g3-Lab/H1ve#12]
### 问题：
我设置的端口号分配是10000~20000，我按例子配置后能够正常运行docker，端口号也能正常变成,10001。但是我自己配置一个题目doker运行起来后端口不能正常的变成10001，而保持原本的docker-compose.yml中的不变。我的系统是ubuntu18.04，docker版本18.09.7，docker-compose版本1.21.2

![image](https://user-images.githubusercontent.com/46131597/71557555-9e68ba00-2a82-11ea-8355-d3ab5469fd10.png)
![image](https://user-images.githubusercontent.com/46131597/71557492-d9b6b900-2a81-11ea-99f7-09d7cbae92c1.png)

我的题目配置：<br>
![image](https://user-images.githubusercontent.com/46131597/71557511-14b8ec80-2a82-11ea-9925-7ad56f26ec5c.png)
![image](https://user-images.githubusercontent.com/46131597/71557516-226e7200-2a82-11ea-840e-9471afb08e15.png)

### 插件配置：<br>
![image](https://user-images.githubusercontent.com/46131597/71557402-9f005100-2a80-11ea-8008-b0f6be1c7857.png)
![image](https://user-images.githubusercontent.com/46131597/71557416-d0791c80-2a80-11ea-841e-a01437710cd5.png)

**Comment by 0akarma** [comment]
配置是没有问题的，只是docker-compose.yml需要注意⚠️两个点：
1.`8087`要改成`9999`（因为后端会根据这个`9999`去动态分配端口）
2.如果后续要用frp动态域名的话，需要将`web`改成`service`

可以参考内置的题型`file-upl0ad`，后续我把注意事项补充到wiki中～感谢

**Comment by Dar1in9s** [comment]
> 配置是没有问题的，只是docker-compose.yml需要注意⚠️两个点：
> 1.`8087`要改成`9999`（因为后端会根据这个`9999`去动态分配端口）
> 2.如果后续要用frp动态域名的话，需要将`web`改成`service`
> 
> 可以参考内置的题型`file-upl0ad`，后续我把注意事项补充到wiki中～感谢
