### ISSUE TITLE
看到一个收费的版本，不晓得是不是你们的，和你们说下

### ISSUE THREAD

**Issue by myxss** [D0g3-Lab/H1ve#49]
地址是这个
https://mall.ti0s.com/

界面很像，有点像二开
![image](https://user-images.githubusercontent.com/33475775/93408966-659a9a80-f8c8-11ea-9780-978a8790ea93.png)

如果是你们团队推出的那就没事了

**Comment by 0akarma** [comment]
感谢提醒，看官网介绍是php写的，应该只是初代版本前端样式是一样。

**Comment by ti0s** [comment]
您好，我是Ti0sCTF平台开发者。感谢您留意Ti0sCTF平台！关于平台是否仿制H1ve开源项目，有利证据已经发至 @0akarma 您的企业邮箱！关于Ti0sCTF平台是否仿制，烦请您 @0akarma 给一个公平的说法！谢谢您！

**Comment by 0akarma** [comment]
> 您好，我是Ti0sCTF平台开发者。感谢您留意Ti0sCTF平台！关于平台是否仿制H1ve开源项目，有利证据已经发至 @0akarma 您的企业邮箱！关于Ti0sCTF平台是否仿制，烦请您 @0akarma 给一个公平的说法！谢谢您！

小事情小事情，[Ti0sCTF](https://mall.ti0s.com/)平台是基于php开发的，只是前端布局雷同，没有所谓的“仿制”一说。
