### ISSUE TITLE
师傅们，攻防对抗赛CTFd版何时开源，期待ing...

### ISSUE THREAD

**Issue by ADOOO** [D0g3-Lab/H1ve#6]
RT

**Comment by 0akarma** [comment]
先放上一张预览图～
![ctfd-glowworm-preview](https://user-images.githubusercontent.com/31059713/71165644-30efa900-228c-11ea-9c1a-3d75f1c96e89.png)

月底之前就会正式开源，因为涉及到一些优化，所以比预先计划的开源时间滞后一点点～感谢理解～

敬请期待！

**Comment by 0akarma** [comment]
https://github.com/D0g3-Lab/H1ve/releases
已经开源了，但是可能还是会有些小bug，欢迎后续继续交流～
