### ISSUE TITLE
owl插件不支持ctfd3.x版本

### ISSUE THREAD

**Issue by captain686** [D0g3-Lab/H1ve#64]
### New Issue Checklist (自检清单)

- [✓] Updated H1ve to the latest version (是否更新到最新版本)
- [✓] I have read the [README](https://github.com/D0g3-Lab/H1ve/blob/master/README.md)
- [✓] I searched for [existing GitHub issues](https://github.com/D0g3-Lab/H1ve/issues)

### Version & Environment (系统/环境版本)
+ Docker Version
+ Docker-compose Version
+ Os Version
+ Browser Version
ctf_owl插件不支持ctfd3.x版本，保存配置的时候404

**Comment by SNCKER** [comment]
同问，有解决方案没，一开始是缺Flask_APScheduler模块，装了之后，保存不了，显示404。
