### ISSUE TITLE
配置完成后web无法建立端口连接udp错误

### ISSUE THREAD

**Issue by cnmstudio** [D0g3-Lab/H1ve#83]
配置后，Direct模式，建立后出现udp错误，无法建立端口连接。
### Issue Description (问题描述)
frpc_1   | 2021/10/24 08:27:49 [I] [admin_api.go:252] Http put request [/api/config]
frpc_1   | 2021/10/24 08:27:49 [I] [admin_api.go:254] Http put response [/api/config], code [200]
frpc_1   | 2021/10/24 08:27:49 [I] [admin_api.go:40] Http request [/api/reload]
frpc_1   | 2021/10/24 08:27:49 [I] [proxy_manager.go:144] [7bdb2397ac572ce0] proxy added: [direct_user1_online_tool_service_1_tcp direct_user1_online_tool_service_1_udp]
frpc_1   | 2021/10/24 08:27:49 [I] [admin_api.go:80] success reload conf
frpc_1   | 2021/10/24 08:27:49 [I] [admin_api.go:42] Http response [/api/reload], code [200]
frps_1   | 2021/10/24 08:27:49 [I] [tcp.go:63] [7bdb2397ac572ce0] [direct_user1_online_tool_service_1_tcp] tcp proxy listen port [33301]
frps_1   | 2021/10/24 08:27:49 [I] [control.go:420] [7bdb2397ac572ce0] new proxy [direct_user1_online_tool_service_1_tcp] success
frps_1   | 2021/10/24 08:27:49 [I] [udp.go:81] [7bdb2397ac572ce0] [direct_user1_online_tool_service_1_udp] udp proxy listen port [33301]
frps_1   | 2021/10/24 08:27:49 [I] [control.go:420] [7bdb2397ac572ce0] new proxy [direct_user1_online_tool_service_1_udp] success
frpc_1   | 2021/10/24 08:27:49 [I] [control.go:164] [7bdb2397ac572ce0] [direct_user1_online_tool_service_1_tcp] start proxy success
frpc_1   | 2021/10/24 08:27:49 [W] [control.go:162] [7bdb2397ac572ce0] [direct_user1_online_tool_service_1_udp] start error: lookup user1_online_tool_service_1 on 127.0.0.11:53: no such host
frps_1   | 2021/10/24 08:27:49 [I] [proxy.go:92] [7bdb2397ac572ce0] [direct_user1_online_tool_service_1_udp] get a new work connection: [10.1.0.4:51356]
frpc_1   | 2021/10/24 08:27:49 [I] [proxy.go:438] [7bdb2397ac572ce0] [direct_user1_online_tool_service_1_udp] incoming a new work connection for udp proxy, 10.1.0.3:80
frpc_1   | 2021/10/24 08:27:54 [I] [admin_api.go:252] Http put request [/api/config]
frpc_1   | 2021/10/24 08:27:54 [I] [admin_api.go:254] Http put response [/api/config], code [200]
frpc_1   | 2021/10/24 08:27:54 [I] [admin_api.go:40] Http request [/api/reload]
frpc_1   | 2021/10/24 08:27:54 [I] [proxy_manager.go:130] [7bdb2397ac572ce0] proxy removed: [direct_user1_online_tool_service_1_tcp direct_user1_online_tool_service_1_udp]
frpc_1   | 2021/10/24 08:27:54 [I] [proxy_manager.go:144] [7bdb2397ac572ce0] proxy added: [direct_user1_online_tool_service_1_udp direct_user1_online_tool_service_1_tcp]
frpc_1   | 2021/10/24 08:27:54 [I] [admin_api.go:80] success reload conf
frps_1   | 2021/10/24 08:27:54 [W] [udp.go:99] [7bdb2397ac572ce0] [direct_user1_online_tool_service_1_udp] read from workConn for udp error: EOF
frpc_1   | 2021/10/24 08:27:54 [I] [admin_api.go:42] Http response [/api/reload], code [200]
frps_1   | 2021/10/24 08:27:54 [I] [proxy.go:92] [7bdb2397ac572ce0] [direct_user1_online_tool_service_1_udp] get a new work connection: [10.1.0.4:51356]
frpc_1   | 2021/10/24 08:27:54 [W] [proxy.go:460] [7bdb2397ac572ce0] [direct_user1_online_tool_service_1_udp] read from workConn for udp error: EOF
frpc_1   | 2021/10/24 08:27:54 [I] [proxy.go:474] [7bdb2397ac572ce0] [direct_user1_online_tool_service_1_udp] writer goroutine for udp work connection closed
frps_1   | 2021/10/24 08:27:54 [I] [proxy.go:76] [7bdb2397ac572ce0] [direct_user1_online_tool_service_1_tcp] proxy closing
frpc_1   | 2021/10/24 08:27:54 [I] [proxy.go:438] [7bdb2397ac572ce0] [direct_user1_online_tool_service_1_udp] incoming a new work connection for udp proxy, 10.1.0.3:80
frps_1   | 2021/10/24 08:27:54 [I] [proxy.go:147] [7bdb2397ac572ce0] [direct_user1_online_tool_service_1_tcp] listener is closed
frps_1   | 2021/10/24 08:27:54 [I] [control.go:429] [7bdb2397ac572ce0] close proxy [direct_user1_online_tool_service_1_tcp] success
frps_1   | 2021/10/24 08:27:54 [I] [proxy.go:76] [7bdb2397ac572ce0] [direct_user1_online_tool_service_1_udp] proxy closing
frps_1   | 2021/10/24 08:27:54 [I] [udp.go:153] [7bdb2397ac572ce0] [direct_user1_online_tool_service_1_udp] sender goroutine for udp work connection closed
frpc_1   | 2021/10/24 08:27:54 [W] [proxy.go:460] [7bdb2397ac572ce0] [direct_user1_online_tool_service_1_udp] read from workConn for udp error: EOF
frps_1   | 2021/10/24 08:27:54 [I] [control.go:429] [7bdb2397ac572ce0] close proxy [direct_user1_online_tool_service_1_udp] success
frps_1   | 2021/10/24 08:27:54 [W] [udp.go:99] [7bdb2397ac572ce0] [direct_user1_online_tool_service_1_udp] read from workConn for udp error: EOF
frps_1   | 2021/10/24 08:27:54 [I] [udp.go:137] [7bdb2397ac572ce0] [direct_user1_online_tool_service_1_udp] sender goroutine for udp work connection closed
frps_1   | 2021/10/24 08:27:54 [I] [tcp.go:63] [7bdb2397ac572ce0] [direct_user1_online_tool_service_1_tcp] tcp proxy listen port [33301]
frps_1   | 2021/10/24 08:27:54 [I] [control.go:420] [7bdb2397ac572ce0] new proxy [direct_user1_online_tool_service_1_tcp] success
frpc_1   | 2021/10/24 08:27:54 [I] [control.go:164] [7bdb2397ac572ce0] [direct_user1_online_tool_service_1_tcp] start proxy success
frps_1   | 2021/10/24 08:27:54 [I] [udp.go:81] [7bdb2397ac572ce0] [direct_user1_online_tool_service_1_udp] udp proxy listen port [33301]
frps_1   | 2021/10/24 08:27:54 [I] [control.go:420] [7bdb2397ac572ce0] new proxy [direct_user1_online_tool_service_1_udp] success
frpc_1   | 2021/10/24 08:27:54 [W] [control.go:162] [7bdb2397ac572ce0] [direct_user1_online_tool_service_1_udp] start error: lookup user1_online_tool_service_1 on 127.0.0.11:53: no such host

### Version & Environment (系统/环境版本)
+ Docker Version  20.10.9, build c2ea9bc
+ Docker-compose Version  1.25.0-rc2, build 661ac20e
+ Os Version centos 7
+ Browser Version

**Comment by LDDP** [comment]
我也是一样的问题

**Comment by cnmstudio** [comment]
> 我也是一样的问题

搞明白了。在docker-compose.yml文件中，端口一定要写 9999:80前面9999不能变，写成9999就都没问题了。至少我这几个题目都成功了。
